### ISSUE TITLE
Missing tag v2

### ISSUE THREAD

**Issue by Dynom** [maxhawkins/google-places-api#9]
Hi Max,

I think you forgot to `git push --tag`? Since I don't see the v2 tag listed, even though you refer to it in commit 473d1c626130a61bd90f15b3d6fa8ecfc5bed5b2

```
curl gopkg.in/maxhawkins/google-places-api.v2/places
GitHub repository at https://github.com/maxhawkins/google-places-api has no branch or tag "v2", "v2.N" or "v2.N.M"
```

Perhaps you can update your travis.yml to "dog food" your package reference URI?

**Comment by maxhawkins** [comment]
Good catch, thanks! It should be updated now.

I think I'll keep the travis.yml pointing to the github repo so that running tests on branches/pull requests continues to work.
